[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vaultbuilder = "GzfCdcY959JzTZMp741SF79eX2YkkYdCv4ZjcwNj5imB"

[programs.devnet]
vaultbuilder = "GzfCdcY959JzTZMp741SF79eX2YkkYdCv4ZjcwNj5imB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = 'C:\Users\RiceTriesNewThings\.openclaw\workspace_Rusty\devnet-vault.json'

[test]
startup_wait = 20000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
